name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # 12시간마다 자동 실행
  workflow_dispatch:        # 버튼 눌러 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: UJin1122
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake file
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate snake animation"
          add: "dist"
